🎉  testing first job

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -20,7 +20,17 @@ jobs:
         with:
           fetch-depth: 0
       - run: |
-          exit 0
+          if find ./ ( -name "#*#" -o -name "*~" -o -name ".o" -o -name "*.a" -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -iname "*pain_au_chocolat*" -o -path "/tmp/" -type f ) -exec false {} +
+            then
+              exit 0
+            else
+              path=$(find ./ ( -name "#*#" -o -name "*~" -o -name "*.o" -o -name "*.a" -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcov" -o -iname "*pain_au_chocolat*" -o -path "/tmp/" -type f ))
+              for i in $path; do
+                 echo "::error file=$i,line=1,endLine=1,title=Unwanted file detected::$i"
+              done
+              exit 1
+            fi
+            exit 0
 
   check_program_compilation:
     needs: check_repository_cleanliness
